ML LAB-7 NAME:ABHISHEK YADAV USN NO:CS23071 AIM:To appply support vector machine for classification and analyze the impact of different kernels on models accuracy.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
path="/content/drive/MyDrive/Dataset_7/pulsar_stars.csv"
df=pd.read_csv(path)
df.head(5)

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve,target_class
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225,0
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580,0
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909,0
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661,0
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306,0

In [ ]:
df.columns = df.columns.str.replace(' ', '_')  # Replaces spaces with underscores
df.columns = df.columns.str.strip()           # Removes leading/trailing spaces

In [ ]:
 print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17898 entries, 0 to 17897
Data columns (total 9 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   _Mean_of_the_integrated_profile                17898 non-null  float64
 1   _Standard_deviation_of_the_integrated_profile  17898 non-null  float64
 2   _Excess_kurtosis_of_the_integrated_profile     17898 non-null  float64
 3   _Skewness_of_the_integrated_profile            17898 non-null  float64
 4   _Mean_of_the_DM-SNR_curve                      17898 non-null  float64
 5   _Standard_deviation_of_the_DM-SNR_curve        17898 non-null  float64
 6   _Excess_kurtosis_of_the_DM-SNR_curve           17898 non-null  float64
 7   _Skewness_of_the_DM-SNR_curve                  17898 non-null  float64
 8   target_class                                   17898 non-null  int64
dtypes: float64(8), int64(1)
memory usage: 1.2 MB
None

In [ ]:
df.shape

(17898, 9)

In [ ]:
df.columns

Index(['_Mean_of_the_integrated_profile',
       '_Standard_deviation_of_the_integrated_profile',
       '_Excess_kurtosis_of_the_integrated_profile',
       '_Skewness_of_the_integrated_profile', '_Mean_of_the_DM-SNR_curve',
       '_Standard_deviation_of_the_DM-SNR_curve',
       '_Excess_kurtosis_of_the_DM-SNR_curve', '_Skewness_of_the_DM-SNR_curve',
       'target_class'],
      dtype='object')

In [ ]:
df.isnull().any().any()

np.False_

In [ ]:
df.isnull().sum()

_Mean_of_the_integrated_profile                  0
_Standard_deviation_of_the_integrated_profile    0
_Excess_kurtosis_of_the_integrated_profile       0
_Skewness_of_the_integrated_profile              0
_Mean_of_the_DM-SNR_curve                        0
_Standard_deviation_of_the_DM-SNR_curve          0
_Excess_kurtosis_of_the_DM-SNR_curve             0
_Skewness_of_the_DM-SNR_curve                    0
target_class                                     0
dtype: int64

In [ ]:
df[df.isnull().any(axis = 1)]

Empty DataFrame
Columns: [_Mean_of_the_integrated_profile, _Standard_deviation_of_the_integrated_profile, _Excess_kurtosis_of_the_integrated_profile, _Skewness_of_the_integrated_profile, _Mean_of_the_DM-SNR_curve, _Standard_deviation_of_the_DM-SNR_curve, _Excess_kurtosis_of_the_DM-SNR_curve, _Skewness_of_the_DM-SNR_curve, target_class]
Index: []

In [ ]:
x = df.drop(columns=['target_class'])
y = df['target_class']

In [ ]:
x.head()

,_Mean_of_the_integrated_profile,_Standard_deviation_of_the_integrated_profile,_Excess_kurtosis_of_the_integrated_profile,_Skewness_of_the_integrated_profile,_Mean_of_the_DM-SNR_curve,_Standard_deviation_of_the_DM-SNR_curve,_Excess_kurtosis_of_the_DM-SNR_curve,_Skewness_of_the_DM-SNR_curve
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306

In [ ]:
x = pd.get_dummies(x, dtype = int)

In [ ]:
x.head()

,_Mean_of_the_integrated_profile,_Standard_deviation_of_the_integrated_profile,_Excess_kurtosis_of_the_integrated_profile,_Skewness_of_the_integrated_profile,_Mean_of_the_DM-SNR_curve,_Standard_deviation_of_the_DM-SNR_curve,_Excess_kurtosis_of_the_DM-SNR_curve,_Skewness_of_the_DM-SNR_curve
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306

In [ ]:
x.shape

(17898, 8)

In [ ]:
x.columns

Index(['_Mean_of_the_integrated_profile',
       '_Standard_deviation_of_the_integrated_profile',
       '_Excess_kurtosis_of_the_integrated_profile',
       '_Skewness_of_the_integrated_profile', '_Mean_of_the_DM-SNR_curve',
       '_Standard_deviation_of_the_DM-SNR_curve',
       '_Excess_kurtosis_of_the_DM-SNR_curve',
       '_Skewness_of_the_DM-SNR_curve'],
      dtype='object')

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, train_size = 0.7, test_size=0.3, random_state = 42)
x_train.shape, x_test.shape

((12528, 8), (5370, 8))

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators=100, n_jobs=-1,max_depth=5, oob_score=True, random_state=42)
rf_classifier.fit(x_train, y_train)

RandomForestClassifier(max_depth=5, n_jobs=-1, oob_score=True, random_state=42)

In [ ]:
y_pred = rf_classifier.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
print('confusion matrix')
cm=confusion_matrix(y_test, y_pred)
print(confusion_matrix(y_test, y_pred))

confusion matrix
[[4862   22]
 [  89  397]]

In [ ]:
print('Accuracy Score:')
print(accuracy_score(y_test, y_pred))

Accuracy Score:
0.9793296089385475

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
svc=SVC()
svc.fit(x_train,y_train)
y_pred=svc.predict(x_test)
print(f'Model accuracy score with default hyperparameters: {accuracy_score(y_test, y_pred):0.4f}')

Model accuracy score with default hyperparameters: 0.9728

In [ ]:
sigmoid_svc100=SVC(keneli='sigmoid',C=100.0)
sigmoid_svc.fit (x_train,y_train)